### PR TITLE
Update ivoatex  

### PR DESCRIPTION
**Pull request by BaptisteCecconi**

### CODE REVIEW

**Comment by msdemlei** [comment]
Could you have a long, hard look at the history of the branch you're trying to merge here?  I'm a bit confused that the diff is small but there are a lot of patches.  I grant you the patches mostly conceren github magic, and I'm not concerned enough to bother investigating this myself.  But briefly ensuring we're not introducing odd branching seems to be a good move here.

**Comment by BaptisteCecconi** [comment]
Sorry, I thought the same when I saw the list of commits... I think this is due to many small fixes that I did on my fork but that I implemented directly on the main repo with PR. The only way I see to solve this out is to erase my fork and my local copy, refork and apply the small patch to the newly forked repo... What do you think ?

**Comment by msdemlei** [comment]
On Wed, May 04, 2022 at 01:39:38AM -0700, Baptiste Cecconi wrote:
> Sorry, I thought the same when I saw the list of commits... I think
> this is due to many small fixes that I did on my fork but that I
> implemented directly on the main repo with PR. The only way I see
> to solve this out is to erase my fork and my local copy, refork and
> apply the small patch to the newly forked repo... What do you think
> ? 

That's (or or less) what a rebase should do.  I'd try a git rebase
master first (note that you'll have to git push -f then).  

Then: If the other commits are already merged (which they seem to
be), then a fresh branch off master and a merge of your current
branch into that ought to give roughly the same result (modulo minor
history cosmetics).

**Comment by BaptisteCecconi** [comment]
I've done the rebase actually, and those are the remaining bits... since the actual changes only concerns the last changes I made, I'm not worried.

**Review by loumir — APPROVED** [review]

**Pull request merged**
