### PR TITLE
updated UCDList.tex

### PR DESCRIPTION
**Pull request by loumir**
grouped amendments in  changes section instr.fov and meta.curation

### CODE REVIEW

**Comment by loumir** [comment]
I think the document is ready now , once this PR is Merged . 
Any more concerns on your side ?

**Comment by msdemlei** [comment]
On Tue, May 10, 2022 at 03:30:04AM -0700, Mireille LOUYS wrote:
> I think the document is ready now , once this PR is Merged . 
> Any more concerns on your side ?

Well, perhaps a quick one: In the PR, you're using \emph to mark up
UCDs.  That's not a mortal sin, but for common appearance and better
hyphenation it's better if you use \ucd whenever the argument
actually is a UCD.  Can I charm you into doing that (preferably in
another commit on this branch)?

**Comment by BaptisteCecconi** [comment]
ok, @msdemlei if you can do this, I'll approve and merge

**Review by BaptisteCecconi — DISMISSED** [review]

**Review by BaptisteCecconi — APPROVED** [review]

**Comment by loumir** [comment]
Ok, great . Thanks for harmonizing the tags. 
Next step is to issue the document to Giulia , our IVOA document Coordinator.  I did not practice yet with the ivoa doc script submission.
Is it up to the Semantics chair to do it , or can I do it myself with the interactive site?

**Comment by msdemlei** [comment]
On Tue, May 10, 2022 at 07:05:01AM -0700, Mireille LOUYS wrote:
> Ok, great . Thanks for harmonizing the tags.  Next step is to issue
> the document to Giulia , our IVOA document Coordinator.  I did not
> practice yet with the ivoa doc script submission.  Is it up to the
> Semantics chair to do it , or can I do it myself with the
> interactive site? 

You could, but there's a lot less that can go wrong when you use make
upload (and there's also the checklist at
https://ivoa.net/documents/Notes/IVOATex/20180814/NOTE-ivoatexDoc-1.2-20180814.html#tth_sEc3.11
that really assumes you can run the various things locally).

So, unless you protest I'd volunteer for uploading.

**Pull request merged**
