### PR TITLE
UCDList: formatting changes, in particular for the main UCD table.

### PR DESCRIPTION
**Pull request by msdemlei**
This commit hopefully improves the formatting of the tables
(mainly the main table).

Essentially, we're widening up the pages a bit and redistribute space so
there's less width wasted in the UCD column for the few very long words.
The very long words we now break like

vaderetro.overfull.hbox.
...patchthis

@BaptisteCecconi: Can you live with that butchering?

### CODE REVIEW

**Comment by msdemlei** [comment]
On Wed, Feb 12, 2020 at 04:56:12AM -0800, Baptiste Cecconi wrote:
> I agree with the spirit of the changes, but I'm not sure the
> double-triple-dot makes it obvious that this is an overflow.  At
> least we need a small sentence explaining how to read correctly
> those split ucd items. 

That would be the easy solution.  I like easy solutions and thus I've
amended the PR with such a sentence.  Would that already work for a
first approximation?

> Then in terms of understandability:
> ```
> phys.polarization...
> ...stokes.Q
> ```
> could be replaced by:
> ```
> phys.polarization.$\vartriangleright$
> $\vartriangleright$stokes.Q
> ```
> NB: `$\vartriangleright$` is part of mismatch package and is a
> right point empty triangle.

Unfortunately, that's not possible with the TeX tech I'm using, which
is \discretionary; you can't have font changes in there.

Now that I look at things again I'd say the ideal wrap style would
probably be

```
|phys.polarization.   |
|             stokes.Q|
```

i.e., just a break and then the second line is set flush right.

But that's actually higher magic (or so I think), and so perhaps we
can merge now and revisit the actual presentation later?

**Comment by BaptisteCecconi** [comment]
There is a typo in the explanation where `some.log.ucd.x` whorl be replaced by `some.long.ucd.x`

**Comment by msdemlei** [comment]
> please check my previous comment (typo on explanation line)

Oops -- missed that mail back in February, sorry.  Fixed the typo now.

**Review by BaptisteCecconi — DISMISSED** [review]

**Comment by BaptisteCecconi** [comment]
@msdemlei, there are merge conflicts to be solved, can you do this?

**Comment by msdemlei** [comment]
On Thu, Apr 08, 2021 at 05:57:50AM -0700, Baptiste Cecconi wrote:
> @msdemlei, there are merge conflicts to be solved, can you do this? 

Well, I hope.  The large changes got both me and git somewhat
confused, and my foolish expectation that a rebase would lead to a
nicer history certainly didn't help.  

Please have a quick look and make sure the changes you made in master
haven't been clobbered.

These diffs won't be pretty any more.  I'd say we live with a
somewhat odd-looking history.  If you want a pretty history, I'd say
we ought to go back to the original PR and merge it into before your
big refactoring.

**Review by BaptisteCecconi — APPROVED** [review]
changes are ok

**Pull request merged**
