### PR TITLE
This is the PEN-1.4 version

### PR DESCRIPTION
**Pull request by BaptisteCecconi**
This version has been prepared with Mireille Louys during the Groningen ADASS-IVOA week. 

The new version of the document contains the new UCD words discussed and accepted by the Semantics Working Group during the UCD list v1.3 RFM.

### CODE REVIEW

**Comment by BaptisteCecconi** [comment]
From what I understand, we have to update the forked repository ([BaptisteCecconi/UCDList:master](https://github.com/BaptisteCecconi/UCDList )), in such a case.

Either you do it (clone, update, commit, push) or I do it, if you tell me the changes to propose. I have added you to my forked repo if you want to do it yourself.

**Comment by BaptisteCecconi** [comment]
ok, then you can review and accept.

**Comment by loumir** [comment]
ok to merge

**Comment by BaptisteCecconi** [comment]
yes ! :-)

**Comment by BaptisteCecconi** [comment]
tu as fait le merge avant de fermer ?

**Comment by BaptisteCecconi** [comment]
yes ! :-)

**Pull request merged**
